version: "3.8"
services:
#  draw2form--llm:
#    container_name: draw2form--llm
#    build:
#      context: llm-api
#      dockerfile: Dockerfile
#    restart: 'no'
#    env_file:
#      - .env
#    ports:
#      - '8001:8001'
  draw2form--chatgpt:
    container_name: draw2form--chatgpt
    build:
      context: chatgpt-api
      dockerfile: Dockerfile
    restart: 'no'
    env_file:
      - .env
    ports:
      - '8002:8002'
