version: "3.8"
services:
  draw2form--postgres:
    container_name: draw2form--postgres
    restart: 'no'
    image: postgres:14.9-alpine3.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: V7NHzBm6U.4-phLzTvJt
  draw2form--postgres2:
    container_name: draw2form--postgres2
    restart: 'no'
    image: postgres:14.9-alpine3.17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: V7NHzBm6U.4-phLzTvJt
