apiVersion: v1
kind: Namespace
metadata:
  name: "app-draw2form"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-draw2form
  namespace: app-draw2form
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deployment-draw2form
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deployment-draw2form
    spec:
      containers:
        - image: ericaskari/draw2form-api:latest
          name: draw2form-api
          imagePullPolicy: Always
          env:
            - name: APP_OAUTH2_CLIENT_ID
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_OAUTH2_CLIENT_ID
            - name: APP_OAUTH2_CLIENT_SECRET
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_OAUTH2_CLIENT_SECRET
            - name: APP_OAUTH2_CALLBACK_URL
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_OAUTH2_CALLBACK_URL
            - name: APP_JWT_SECRET
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_JWT_SECRET
            - name: APP_SESSION_SECRET
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_SESSION_SECRET
            - name: APP_ANDROID_SHA256_CERT_FINGERPRINT
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_ANDROID_SHA256_CERT_FINGERPRINT
            - name: APP_JWT_ISSUER
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_JWT_ISSUER
            - name: APP_JWT_AUDIENCE
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_JWT_AUDIENCE
            - name: APP_DATABASE_URL
              value: op://Metropolia/deployment-draw2form-$APP_ENV/infra/APP_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: service-draw2form
  namespace: app-draw2form
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: deployment-draw2form
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-draw2form
  namespace: app-draw2form
spec:
  tls:
    - hosts:
        - draw2form.ericaskari.com
      secretName: ericaskari-com-tls-secret
  rules:
    - host: draw2form.ericaskari.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-draw2form
                port:
                  number: 8000
