version: "3.8"
services:
  sbma--postgres:
    container_name: sbma--postgres
    restart: 'no'
    image: postgres:14.9-alpine3.17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: V7NHzBm6U.4-phLzTvJt
