name: API Deployment
on:
  push:
    branches: [ backend-api ]
permissions: write-all

jobs:
  Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd api && npm ci
      - run: cd api && npm run build



