name: Pull Request Tests
on:
  pull_request:
jobs:
  BuildLLMApiDocker:
    runs-on: ubuntu-latest
    steps:
      - name: "Git: Pull Source Code"
        uses: actions/checkout@v3
      - name: "Docker: Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Docker: Set up Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Docker: Build And Push Image"
        uses: docker/build-push-action@v5
        with:
          context: llm-api
          file: llm-api/Dockerfile
          push: true
          tags: ericaskari/draw2form-llm-api:latest,ericaskari/draw2form-llm-api:${{needs.Version.outputs.version}}
          cache-from: type=registry,ref=ericaskari/draw2form-llm-api:latest
          cache-to: type=inline
  BuildApiDocker:
    runs-on: ubuntu-latest
    steps:
      - name: "Git: Pull Source Code"
        uses: actions/checkout@v3
      - name: "Docker: Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Docker: Set up Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Docker: Build And Push Image"
        uses: docker/build-push-action@v5
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: ericaskari/draw2form-api:latest,ericaskari/draw2form-api:${{needs.Version.outputs.version}}
          cache-from: type=registry,ref=ericaskari/draw2form-api:latest
          cache-to: type=inline
