name: Build And Deployment
on:
  pull_request:
jobs:
  BuildDocker:
    runs-on: ubuntu-latest
    needs: [ Version ]
    steps:
      - name: "Git: Pull Source Code"
        uses: actions/checkout@v3
      - name: "Docker: Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Docker: Set up Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Docker: Build Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ericaskari/llm-wireframe:latest,ericaskari/llm-wireframe:${{needs.Version.outputs.version}}
          cache-from: type=registry,ref=ericaskari/llm-wireframe:latest
          cache-to: type=inline
