name: Build And Deployment
on:
  workflow_dispatch:
  push:
    branches: [ main, cicd ]
jobs:
  Train:
    runs-on: self-hosted
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      - name: Train
        shell: C:\Users\Eric\miniconda3\Scripts\activate.bat
        run: |
          C:\Users\Eric\miniconda3\Scripts\activate.bat
          dir
          python train.py