name: Build And Deployment
on:
  workflow_dispatch:
  push:
    branches: [ main, cicd ]
permissions: write-all
jobs:
  GetLatestTag:
    runs-on: ubuntu
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: Get Latest Tag
        id: previoussemver
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0
      - name: Get Next Tag
        id: nextsemver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoussemver.outputs.tag }}
      - name: Debug
        shell: bash
        run: echo ${{ steps.nextsemver.outputs.patch }}
      - name: Create new milestone
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.nextsemver.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Push new tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ steps.nextsemver.outputs.patch }}
          git_tag_prefix: ""
    outputs:
      oldversion: ${{ steps.previoussemver.outputs.tag }}
      version: ${{ steps.nextsemver.outputs.patch }}

  Build:
    runs-on: ubuntu
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


#  Train:
#    runs-on: self-hosted
#    steps:
#      - name: Pull Source Code
#        uses: actions/checkout@v3
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          python-version: ${{ matrix.python-version }}
#      - name: Conda info
#        shell: bash -el {0}
#        run: conda info
#      - name: Conda list
#        shell: pwsh
#        run: conda list
#      - name: Train
#        shell: C:\Users\Eric\miniconda3\Scripts\activate.bat
#        run: |
#          C:\Users\Eric\miniconda3\Scripts\activate.bat
#          dir
#          python train.py
