name: Build And Deployment
on:
  workflow_dispatch:
  push:
    branches: [ main, cicd ]
jobs:
  Train:
    runs-on: self-hosted
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
#      - name: Train
#        shell: C:\Users\Eric\miniconda3\Scripts\activate.bat
#        run: |
#          C:\Users\Eric\miniconda3\Scripts\activate.bat
#          dir
#          python train.py