name: Train Model
on:
  workflow_dispatch:
  push:
    branches: [ train-cicd ]
permissions: write-all

jobs:
  Train:
    runs-on: self-hosted
    env:
      APP_ROBEFLOW_API_KEY: ${{ secrets.APP_ROBEFLOW_API_KEY }}
    steps:
      - name: "Git: Pull Source Code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python information
        shell: bash
        run: |
          python --version || true
      - name: Conda information
        shell: bash
        run: |
          conda --version || true
      - name: Conda information
        shell: bash
        run: |
          conda --version || true
      - name: Train Model
        shell: bash
        run: |
          python train.py
      - name: Generate Build Version
        id: generateversion
        shell: bash
        run: |
          version="$(date +%Y-%m-%d-%H-%M)"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Upload Trained Model
        uses: actions/upload-artifact@v3
        with:
          name: model-${{ steps.generateversion.outputs.version }}
          path: /root/miniconda3/lib/python3.11/site-packages/tests/tmp/runs/detect/train
