name: Train Model
on:
  workflow_dispatch:
  push:
    branches: [ train-cicd ]
permissions: write-all

jobs:
  Version:
    runs-on: self-hosted
    steps:
      - name: "Git: Pull Source Code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python information
        shell: bash
        run: |
          python --version || true
      - name: Conda information
        shell: bash
        run: |
          conda --version || true
      - name: Train Model
        shell: bash
        run: |
          python train.py
      - uses: actions/upload-artifact@v3
        with:
          name: Upload Trained Model
          path: /root/miniconda3/lib/python3.11/site-packages/tests/tmp/runs/detect/train
